networks:
  my-isolated-network:
    name: dungeons-and-dragons

services:
  adventurer:
    image: ghcr.io/guggisbergsimon/dai-pw3:v1.0
    command:
      - adventurer
      - --host=billboard
      - --unicastPort=32000

  guild:
    image: ghcr.io/guggisbergsimon/dai-pw3:v1.0
    command:
      - guild
      - --host=239.1.1.1
      - --multicastPort=42000
      - --interface=eth0

  billboard:
    image: ghcr.io/guggisbergsimon/dai-pw3:v1.0
    command:
      - billboard
      - --host=239.1.1.1
      - --multicastPort=42000
      - --unicastPort=32000
      - --interface=eth0