networks:
  my-isolated-network:
    name: dungeons-and-dragons

services:
  adventurer:
    image: ghcr.io/heig-vd-dai-course/java-udp-programming
    command:
      - adventurer
      - --host=239.1.1.1
      - --port=32000

  guild:
    image: ghcr.io/heig-vd-dai-course/java-udp-programming
    command:
      - guild
      - --host=239.1.1.1
      - --port=42000
      - --interface=eth0
    networks:
      - dungeons-and-dragons

  billboard:
    image: ghcr.io/heig-vd-dai-course/java-udp-programming
    command:
      - billboard
      - --host=239.1.1.1
      - --multicastPort=42000
      - --port=32000
      - --interface=eth0
    networks:
      - dungeons-and-dragons
